### ISSUE TITLE
Move bspkrs mods from .version polling to DB-index

### ISSUE THREAD

**Issue by helinus** [NotEnoughMods/NotEnoughModPolling#14]
As it is now only 1.6.4 versions of his mods are polled, by checking db-index pages instead of the .version files NEMP can catch all mc versions.

db-index page for treecap as an example: http://bspk.rs/MC/TreeCapitator_Forge/index.html

**Comment by NightKev** [comment]
I don't think this is a good idea, it would rely on some, well, unreliable html parsing that could change at any point in the future. There's other (hopefully better) ways of doing this.
