### ISSUE TITLE
Add Reika's mods to nemp

### ISSUE THREAD

**Issue by bochen415** [NotEnoughMods/NotEnoughModPolling#141]
As title
Invent CheckReika, ask the author for permission
https://github.com/ReikaKalseki/DragonAPI/blob/master/Auxiliary/Trackers/CommandableUpdateChecker.java

**Comment by SinZ163** [comment]
asking author for permission shouldn't be required.

**Comment by bochen415** [comment]
Yes, you're right, I thought the url generation was more complicated but as it turns out it's super simple.
http://server.techjargaming.com/Reika/versions_1-7-10.txt
Hmm... the "V" isn't there, like in the mcmod.info files.

**Comment by dmodoomsirius** [comment]
Next Release Reika will be uploading to curse. Closing since we can poll curse.

**Comment by bochen415** [comment]
Glad to hear. Thanks

**Comment by SinZ163** [comment]
Implemented in 47a0009497bb
