### ISSUE TITLE
Add other micdoodle mod jenkins polling

### ISSUE THREAD

**Issue by mskurnik** [NotEnoughMods/NotEnoughModPolling#162]
There are two other mods that can be added and tracked via the "Galacticraft" Jenkins page.
-  `"MicdoodleCore-.+?-(?P<dev>.+?).jar"`
-  `"Galacticraft-Planets-.+?-(?P<dev>.+?).jar"`

MicdoodleCore is a requirement of Galacticraft.
Galacticraft Planets requires the other two mods.

**Comment by dmodoomsirius** [comment]
I will work on this soon.

**Comment by SinZ163** [comment]
Soon™

**Comment by dmodoomsirius** [comment]
Will be added in my next commit.
