### ISSUE TITLE
Add TickProfiler

### ISSUE THREAD

**Issue by LunNova** [NotEnoughMods/NotEnoughModPolling#167]
Using the Jenkins folder plugin, it's possible to organise versions in folders.

https://nallar.me/buildservice/job/TickProfiler/

/job/_MODNAME_/branch/_MCVERSION_

[A request to /job/_MODNAME_/api/json.](https://gist.github.com/nallar/5843a729fa4576b14670)

Could you add support for polling Jenkins when organised like this? Each folder represents an MC version, if the name doesn't match an MC version exactly it should be skipped?

If you're okay with adding support for this, I can write a PR to add the feature. No guarantees about high quality code, haven't used Python in some time :(

**Comment by SinZ163** [comment]
thats just a matter of updating the url field in mods.json

**Comment by LunNova** [comment]
Won't that require adding a new entry to the mods.json every time I add a new MC version?

**Comment by LunNova** [comment]
If it's okay to just add lots of separate job URLs, here are the current ones:

ModPatcher 1.7.10 https://nallar.me/buildservice/job/ModPatcher/branch/1.7.10/
ModPatcher 1.8.9 https://nallar.me/buildservice/job/ModPatcher/branch/1.8.9/
ModPatcher 1.10 https://nallar.me/buildservice/job/ModPatcher/branch/1.10/

NTweaks 1.7.10 https://nallar.me/buildservice/job/NTweaks/branch/1.7.10/

TickProfiler 1.7.10 https://nallar.me/buildservice/job/TickProfiler/branch/1.7.10/
TickProfiler 1.8.9 https://nallar.me/buildservice/job/TickProfiler/branch/1.8.9/
TickProfiler 1.10 https://nallar.me/buildservice/job/TickProfiler/branch/1.10/

**Comment by LunNova** [comment]
Any update on this? Do you want a PR adding them to `mods.json`?

**Comment by NightKev** [comment]
Ah yeah, that'd be good.

**Comment by NightKev** [comment]
@nallar It seems like your server is down, is this temporary?

**Comment by LunNova** [comment]
Yes, sorry about that. nginx keeps locking up and I'm not sure why. Haven't had time to diagnose it.

e: Workaround of sending nginx reload signal every 5 minutes added since that seems to fix it. Will probably never get around to actually fixing it now there's a "temporary" fix

**Comment by NightKev** [comment]
Heh, gotcha, I'll get to adding the mods then.

**Comment by NightKev** [comment]
For ModPatcher, all the builds just have "SNAPSHOT" as their version, so you'll have to change your buildscript to use the build number or something otherwise there's not much point in tracking that one.

Also there are no builds for NTweaks at all so I guess that mod got scrapped?

**Comment by NightKev** [comment]
@nallar TickProfiler added, but I can't add ModPatcher until it's changed.

**Comment by LunNova** [comment]
Sorry about the delay. Don't bother with NTweaks or TickProfiler, not much point in keeping track of either of them here since one is a library only used by me and the other is now a dead project...

TickProfiler is now published to curseforge. Could you change polling it to use https://minecraft.curseforge.com/projects/tickprofiler/files instead of hitting my jenkins?

**Comment by Pyker** [comment]
@nallar Updated! Is there anything else that's needed to close this issue?

**Comment by LunNova** [comment]
That's all. Thanks!
