### ISSUE TITLE
Additional Data Source from Curseforge

### ISSUE THREAD

**Issue by mskurnik** [NotEnoughMods/NotEnoughModPolling#183]
I decided to do some investigating today and found out the URL that the Curse Client pulls it data from.  You can pull a BZ2 compressed archive of a JSON file.  The archive is around 3MB but expands to about 42MB as of today.  You can access it via HTTP GET at http://clientupdate-v6.cursecdn.com/feed/addons/432/v10/complete.json.bz2?t=1464988120522.  The Query string of "t" is the UNIX time with milliseconds and may not be needed.

The data source has a "LatestFiles" object that contains a "GameVersion" that can be easily filtered.

I think if you can parse this data (I have already successfully done so in C#) that you could eliminate every single individual call to widget.mcf.li.

There also is an "hourly" feed that contains, what I assume to be, the changes to mods in the database from the last hour.  That can be accessed at http://clientupdate-v6.cursecdn.com/feed/addons/432/v10/hourly.json.bz2.

I am in no way suggesting that you import all of the mods that are in that feed but instead to simply poll that source for information about the mods that are the community wants to see.

---

I also found 2 SOAP web services which can let you get information about specific mods.  It requires you to [authenticate](https://clientservice-v6-beta.curse.com/ClientLoginService.svc) with a Curse user/pass on one service in order to get a token that can be used with the [other service](https://addon-service.curse.com/AddOnService.svc) to get a lot of other data.

---

There are a few other services that Curse uses but none that really help with polling mod data.

**Comment by mskurnik** [comment]
Here is a [GIST](https://gist.github.com/mskurnik/5b0b7a758d9a7af0f26fd7a9d48b2ebb) of the classes I created to deserialize the data.  This was not necessary but is useful for debugging and development.

I was told that wasn't very useful in IRC so here is the most useful information:
`data.data.Take(100).Select(x => new { x.GameVersionLatestFiles }).Dump();`

That will give you something like this:

| GameVesion | ProjectFileID | ProjectFileName | FileType |
| --- | --- | --- | --- |
| 1.0.0 | 554368 | JourneyMap1.0.0_MC1.0.0.zip | 1 |
| 1.1 | 568433 | JourneyMap1.0.1_MC1.1.zip | 1 |
| 1.4.7 | 683238 | JourneyMap1.9.1_MC1.4.6.zip | 1 |
| 1.5.2 | 717862 | JourneyMap2.6.1_MC1.5.2.zip | 1 |
| 1.6.4 | 2209902 | JourneyMap4.0.3_Unlimited_MC1.6.4.jar | 1 |
| 1.7.2 | 2209904 | JourneyMap4.0.3_Unlimited_MC1.7.2.jar | 1 |
| 1.7.10 | 2296716 | journeymap-1.7.10-5.1.4p1 | 1 |
| 1.8 | 2269316 | journeymap-1.8-5.1.3 | 1 |
| 1.8 | 2256041 | journeymap-1.8-5.1.1b6-fairplay.jar | 2 |
| 1.8.9 | 2303254 | journeymap-1.8.9-5.2.0 | 1 |
| 1.8.9 | 2295027 | journeymap-1.8.9-5.2.0b1 | 2 |
| 1.8.8 | 2269324 | journeymap-1.8.8-5.1.3 | 1 |
| 1.9 | 2303345 | journeymap-1.9-5.2.0 | 1 |
| 1.9 | 2295029 | journeymap-1.9-5.2.0b1 | 2 |
| 1.9.4 | 2303349 | journeymap-1.9.4-5.2.0 | 1 |

**Comment by mskurnik** [comment]
Be aware that in my own testing I have found at least 2 mods that do not appear in that list but do on their website so you may need to do a check against that.

**Comment by mskurnik** [comment]
In my own tests with C#, I have found that using the WCF SOAP service is actually quicker in performing checks as you don't have to download, extract, deserialize, search.  It was taking me 9 seconds or so to load and process my mods with the feed.  I used the GetAddOnsAsync(int[] ids) with IDs I needed to check and it went down to less than 1 second.  With that said I have no idea how hard that is to do in python.

**Comment by johnlage** [comment]
Hey, do you still have the code that you used for the SOAP services? I was looking to do something using the SOAP service (in python), and planned on reusing my code to contribute to NEM, but can't figure out how to do the Binary XML thing for the Auth service.

**Comment by Pyker** [comment]
This API is now dead, so I'm closing this.
