### ISSUE TITLE
Mods to add

### ISSUE THREAD

**Issue by dmodoomsirius** [NotEnoughMods/NotEnoughModPolling#185]
- [x] Chisel http://minecraft.curseforge.com/projects/chisel (tterrag)
- [x] forge for 1.9
- [x] forge for 1.9.4
- [x] forge for 1.10
- [x] https://github.com/NotEnoughMods/NotEnoughModPolling/issues/162

I will add these when i get up just putting here as a reminder.

**Comment by dmodoomsirius** [comment]
If there are mods to be added please comment on here i will add them to the todo list and add them as i get around it it.

**Comment by dmodoomsirius** [comment]
https://github.com/NotEnoughMods/NotEnoughModPolling/compare/ea0969ac1418...cb78f293236b

**Comment by dmodoomsirius** [comment]
https://github.com/NotEnoughMods/NotEnoughModPolling/compare/cb78f293236b...78335f178f79

**Comment by dmodoomsirius** [comment]
https://github.com/NotEnoughMods/NotEnoughModPolling/compare/78335f178f79...bc12bcca9117

**Comment by gabizou** [comment]
If you can add SpongeForge, still hosted at [files.minecraftforge.net](http://files.minecraftforge.net/maven/org/spongepowered/spongeforge/index_1.10.2.html) for both 1.8.9 and 1.10.2 (1.9.4 development was dropped).

All releases currently are marked as BETA for the fact that the API is in beta development (and likewise the implementation). 

The versioning scheme for SF is slightly different: <SpongeAPI>-BETA-<BuildNumber>.

**Comment by Pyker** [comment]
SpongeForge added in 0ea805e.

**Comment by Pyker** [comment]
I'm closing this now. If there are future mod requests a new issue should be created.
