### ISSUE TITLE
Polling problem?

### ISSUE THREAD

**Issue by AnarchySage** [NotEnoughMods/NotEnoughModPolling#194]
I tryed to fix my mod on the polling check, but i seem to have done it wrong, its vanityblocks.

**Comment by SinZ163** [comment]
1. The changes were never sent to the bot.
2. The URL supplied was wrong as it was missing http://

**Comment by AnarchySage** [comment]
This didnt seem to fix it, i pushed a build and nothing happened :/

Edit: it updated but still appears odd.

[¤10:21:40:AM¤](ModBot-PM) [1.7.10] VanityBlocks 1.7.10--B89 [B95] http://goo.gl/G9UeqY

Why b89 [B95]?

**Comment by dmodoomsirius** [comment]
ahh the regex for VanityBlocks is set to update the dev. thats why. the 1.7.10--B89 is the version the [B95] is the development version. https://github.com/NotEnoughMods/NotEnoughModPolling/blob/master/NEMP/mods.json#L392
