### ISSUE TITLE
Move some mods from Curse checking to Jenkins checking

### ISSUE THREAD

**Issue by CaitlynMainer** [NotEnoughMods/NotEnoughModPolling#210]
I meant to open this issue a few weeks ago when I asked the question on IRC, I have a few curse projects that have multiple MC versions that don't update when I run multiple builds and publish them to curse.  The suggestion was to open an issue here to have them moved to checking Jenkins, the mods in question are:
OpenPrinter:
1.7 -> http://ci.pc-logix.com/job/OpenPrinter1.7/
1.8.9 -> http://ci.pc-logix.com/job/OpenPrinter-1.8.9/
1.9.4/1.10.2 -> http://ci.pc-logix.com/job/OpenPrinter-1.9.4/

OpenFM:
1.7 -> http://ci.pc-logix.com/job/OpenFM/
1.8.9 -> http://ci.pc-logix.com/job/OpenFM-1.8/
1.9.4 -> http://ci.pc-logix.com/job/OpenFM-1.9.4/

OpenSecurity:
1.7 -> http://ci.pc-logix.com/job/OpenSecurity/
I'll be adding other MC versions of this one soon(tm)

Thanks!

**Comment by NightKev** [comment]
@CaitlynMainer Are you going to update the 1.7 version of OpenPrinter in the future? The last build was March of 2016 so if it's a finished mod+mcver there's no reason to add it to renol.

**Comment by CaitlynMainer** [comment]
It's already in renol, I'm just wanting to switch from curse to jenkins, and bug fix builds may happen, it's hard to tell.

**Comment by NightKev** [comment]
Alright, I'll add that one to the json as well.
