### ISSUE TITLE
Add Delta SGCraft polling

### ISSUE THREAD

**Issue by NightKev** [NotEnoughMods/NotEnoughModPolling#28]
http://neo.pc-logix.com:8080/job/Delta%20SGCraft/lastSuccessfulBuild/

**Comment by Pyker** [comment]
The mentioned URL is dead and I can't find info on the mod. It looks like it's called [LanteaCraft](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292427-lanteacraft) now?

**Comment by NightKev** [comment]
Completed with 3c8738d.
