### ISSUE TITLE
Updating of some mods (e.g. SpaceCore) uses wrong list due to name collision 

### ISSUE THREAD

**Issue by RenolY2** [NotEnoughMods/NotEnoughModPolling#36]
A mod that uses the same name on two or more Minecraft versions will not be updated correctly due to a limitation of the code. Mods are added to the self.mods dict using their name, so a mod that is available for at least two different Minecraft versions will have its version set to the version that is looked up last.

This results in the wrong version being used when NEMP updates a mod.

**Comment by SinZ163** [comment]
No way to fix it for mod polling that doesn't tell me the mod version, though Spacechase's mods are fixed by not hardcoding "6"
