### ISSUE TITLE
Add CurseForge polling capability

### ISSUE THREAD

**Issue by matthewprenger** [NotEnoughMods/NotEnoughModPolling#43]
http://widget.mcf.li/mc-mods/minecraft/forgeservertools.json

This is a JSON interface that could be used. Just replace `forgeservertools` with the project ID. For new projects you have to use the ID as well as the name: http://widget.mcf.li/mc-mods/minecraft/220714-servertools-permission.json

**Comment by helinus** [comment]
@matthewprenger, the two latest files are missing from http://widget.mcf.li/mc-mods/minecraft/tinkers-mechworks.json, what's up with that?

**Comment by matthewprenger** [comment]
Hmm not sure. I didn't create it, just stumbled upon it and figured it could be useful.

**Comment by helinus** [comment]
i think i've found out why; some curseforge projects are marked as experimental  and are therefore  not synced to curse.com, this marking is unfortunately not shown anywhere.

**Comment by GenPage** [comment]
Also, the widget JSON interface is not a "true" API. The widget system scrap the html pages off of CurseForge for data and caches it.
