### ISSUE TITLE
Multiple NEM MC versions per mod

### ISSUE THREAD

**Issue by Pyker** [NotEnoughMods/NotEnoughModPolling#98]
Change NEMP (probably in `InitiateVersions` and related code) to get all NEM versions for a mod. This would probably remove all the startup spam from the first polling iteration, because NEMP doesn't know what the NEM version for the mod is when it's not the latest list the mod is in.

**Comment by Pyker** [comment]
Tagged as bug due to the amount of spam it generates on the first run.

**Comment by dmodoomsirius** [comment]
spam only happens on reload. turning it off without reloading and back on does not cause the spam.
